name: Validate Merge & Build

on:
  push:
    branches:
      - main
    paths:
      - "data/newPuzzles.js"
      - "mergePuzzles.js"
      - ".github/workflows/merge.yml"

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Merge puzzles
        run: node mergePuzzles.js

      - name: Commit merged puzzles
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add data/puzzles.js data/newPuzzles.js
          git commit -m "🤖 Auto-merge new puzzle(s)"
          git push
        continue-on-error: true

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test
